"""Build the opponent-deck train/holdout split for the deck-diversity
generalization experiment (notes/experiments/2026-08-05-opponent-deck-diversity-selfplay.md).

WHY MULTISET IDENTITY, NOT BYTE IDENTITY
----------------------------------------
`deck_pool._dedup_by_content` hashes file BYTES, so two files listing the same
60 cards in a different order (or with different whitespace) count as two
"distinct" decks. For a train/holdout split that is a leak: a "held-out" deck
could be a reordering of a training deck. The engine shuffles the submitted
list anyway, so the true identity of a deck is the MULTISET of its 60 card
ids. This script groups the legality-verified pool (all 33 byte-distinct refs
in configs/deck_pools/legal_agents.txt passed scripts/probe_deck_legality.py)
by multiset and splits at the group level.

PINS (forced into TRAIN, never holdout)
---------------------------------------
- il_agent          : the learner's own bundled deck (Mega Lucario ex). The
                      mirror/league buckets play it constantly; holding it out
                      would make the "held-out" battery partly on-distribution.
- kiyotah_dragapult,
  mechi22_alakazam,
  plamen06_steel    : the module opponents in the training mix serve their own
                      bundled decks in BOTH arms, so those decks are trained-on
                      by construction and cannot be holdout.

The remaining multiset groups are shuffled with a fixed seed and the first
HOLDOUT_N become the holdout battery; everything else goes to train. Output
manifests use agent-NAME refs (resolved via agents/<name>/deck.csv by
deck_pool.resolve_deck_ref), not absolute paths, so they survive worktrees.

Usage:
    uv run python scripts/build_opp_deck_split.py
"""
from __future__ import annotations

import random
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))
from pokemon_tcg.deck_pool import parse_deck  # noqa: E402

AGENTS_DIR = REPO / "agents"
OUT_DIR = REPO / "configs" / "deck_pools"
LEGAL = OUT_DIR / "legal_agents.txt"

PINS = ["il_agent", "kiyotah_dragapult", "mechi22_alakazam", "plamen06_steel"]
HOLDOUT_N = 8
SEED = 42


def main() -> None:
    # Re-anchor the legality pass-list to THIS repo's agents/ by name; the
    # file's absolute paths point into the worktree that ran the probe.
    names = [Path(ln.split("#", 1)[0].strip()).parent.name
             for ln in LEGAL.read_text().splitlines()
             if ln.strip() and not ln.lstrip().startswith("#")]
    groups: dict[tuple, list[str]] = {}
    for name in sorted(set(names) | set(PINS)):
        path = AGENTS_DIR / name / "deck.csv"
        if not path.exists():
            raise FileNotFoundError(f"agents/{name}/deck.csv missing here")
        key = tuple(sorted(parse_deck(path)))
        assert len(key) == 60, f"{name}: {len(key)} cards"
        groups.setdefault(key, []).append(name)

    pinned_keys = {tuple(sorted(parse_deck(AGENTS_DIR / p / "deck.csv")))
                   for p in PINS}
    free = sorted(k for k in groups if k not in pinned_keys)
    random.Random(SEED).shuffle(free)
    holdout_keys = free[:HOLDOUT_N]
    train_keys = free[HOLDOUT_N:] + sorted(pinned_keys)

    def rep(key: tuple) -> str:
        members = groups[key]
        for p in PINS:               # pinned name represents its group
            if p in members:
                return p
        return members[0]

    def write(path: Path, keys: list[tuple], label: str) -> list[str]:
        reps = sorted(rep(k) for k in keys)
        lines = [f"# {label} — opponent-deck split, multiset-level, seed={SEED}",
                 f"# generated by scripts/build_opp_deck_split.py from {LEGAL.name}",
                 "# groups (aliases share the same 60-card multiset):"]
        for k in sorted(keys, key=rep):
            lines.append(f"#   {rep(k)}: {', '.join(sorted(groups[k]))}")
        lines += reps
        path.write_text("\n".join(lines) + "\n")
        return reps

    train = write(OUT_DIR / "opp_train.txt", train_keys, "TRAIN pool")
    hold = write(OUT_DIR / "opp_holdout.txt", holdout_keys, "HOLDOUT battery")
    overlap = set(train) & set(hold)
    assert not overlap, f"split leak: {overlap}"
    print(f"{len(groups)} multiset-distinct decks "
          f"({len(names)} byte-distinct refs + pins)")
    print(f"train {len(train)}: {', '.join(train)}")
    print(f"holdout {len(hold)}: {', '.join(hold)}")


if __name__ == "__main__":
    main()
